# Generated by Django 3.2.7 on 2021-09-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_title', models.CharField(max_length=100)),
                ('image_path', models.TextField()),
                ('movie_overview', models.TextField()),
                ('movie_votes', models.FloatField()),
            ],
        ),
    ]
